### ISSUE TITLE
How to download the ZhuXian dataset?

### ISSUE THREAD

**Issue by fake-warrior8** [JZX555/FGDA#1]
Hi, your paper said that the ZhuXian dataset can be downloaded from the paper of "Type-Supervised Domain Adaptation for Joint Segmentation and POS-Tagging". However, I only found two download link in their paper: "https://people.sutd.edu.sg/%cb%9cyue_zhang/eacl14meishan.zip" and "https://people.sutd.edu.sg/%cb%9cyue%20zhang/emnlp12yang.zip", but both these two pages showed  404 Not Found Error. Then, how can I download the ZhuXian dataset?

**Comment by JZX555** [comment]
If those two pages are invalid, you can try to download it from the link below: <https://zhangmeishan.github.io/eacl14mszhang.zip>.

**Comment by fake-warrior8** [comment]
> If those two pages are invalid, you can try to download it from the link below: https://zhangmeishan.github.io/eacl14mszhang.zip.

It works. Thank you!
